apiVersion: v1
kind: Pod
metadata:
  name: good
spec:
  containers:
    - command:
        - etcd
        - --peer-cert-file=file.pem
        - --peer-key-file=file.key
      name: good-container
      image: k8s.gcr.io/etcd-amd64:3.2.18
      imagePullPolicy: IfNotPresent
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/etcd
          name: etcd-data
        - mountPath: /etc/kubernetes/pki/etcd
          name: etcd-certs
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
    - hostPath:
        path: /var/lib/etcd
        type: DirectoryOrCreate
      name: etcd-data
    - hostPath:
        path: /etc/kubernetes/pki/etcd
        type: DirectoryOrCreate
      name: etcd-certs
status: {}