fail:
- beginLine: 4
  detector: api_server_kubelet_client_cert_and_key
  endLine: 4
  explanation: Ensure that the --kubelet-client-certificate and --kubelet-client-key
    arguments are set as appropriate
  file: api_server_kubelet_client_cert_and_key/bad.yaml
  framework: kubernetes
  provider: kubernetes
  resource: bad.yaml.bad
