apiVersion: v1
kind: Pod
metadata:
  name: bad
spec:
  containers:
    - command:
        - etcd
        - --client-cert-auth=false
      name: bad-container
      image: k8s.gcr.io/etcd-amd64:3.2.18
      imagePullPolicy: IfNotPresent
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/etcd
          name: etcd-data
        - mountPath: /etc/kubernetes/pki/etcd
          name: etcd-certs
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
    - hostPath:
        path: /var/lib/etcd
        type: DirectoryOrCreate
      name: etcd-data
    - hostPath:
        path: /etc/kubernetes/pki/etcd
        type: DirectoryOrCreate
      name: etcd-certs
status: {}