kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: good
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["approve"]
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["update", "patch", "get"]